language: rust
env:
  global:
    - RUSTFLAGS="-D warnings"
matrix:
  include:
    - rust: stable
      env: RUST_CHANNEL=stable
    - rust: beta
      env: RUST_CHANNEL=beta
    - rust: nightly
      env: RUST_CHANNEL=nightly
  allow_failures:
    - rust: nightly
  fast_finish: true
install:
  - rustup component add clippy rustfmt
  - if [ $RUST_CHANNEL == "nightly" ]; then
    cargo install cargo-expand;
    fi
script:
  - cargo build --verbose
  - cargo test --verbose
  - cargo fmt -- --check
  - cargo clippy --all-targets
  - if [ $RUST_CHANNEL == "nightly" ]; then
    cargo expand --lib | wc;
    fi
